In [1]:
import numpy as np
import pandas as pd


1. How likely is it that you roll doubles when rolling two dice?


In [2]:
n_trials = n_rows = 100_000

n_dice = ncols =2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(n_rows, ncols)
rolls


array([[6, 5],
       [2, 6],
       [6, 4],
       ...,
       [1, 5],
       [3, 1],
       [1, 1]])

In [3]:
def doubles(rolls):
    return np.array([roll[0] == roll[1] for roll in rolls])
doubles_bool = doubles(rolls)
doubles_bool

array([False, False, False, ..., False, False,  True])

In [4]:
doubles_likely = doubles_bool.mean()
doubles_likely

0.16516

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
n_trials = 100_000
n_coins = 8

In [6]:
flips = np.random.choice([0,1], size=(n_trials, n_coins))
flips = pd.DataFrame(flips)
flips

0  1  2  3  4  5  6  7
0      0  0  0  0  1  0  1  1
1      1  1  0  1  1  0  0  1
2      1  1  1  0  1  1  1  0
3      0  1  1  1  1  1  1  0
4      1  1  1  0  1  0  0  1
...   .. .. .. .. .. .. .. ..
99995  1  1  0  1  0  1  0  0
99996  1  0  0  1  0  0  1  0
99997  0  0  1  1  1  1  1  1
99998  0  1  1  1  0  1  0  1
99999  0  1  1  1  1  0  1  1

[100000 rows x 8 columns]

In [7]:
flips['n_heads'] = flips.sum(axis=1)
flips.head()

0  1  2  3  4  5  6  7  n_heads
0  0  0  0  0  1  0  1  1        3
1  1  1  0  1  1  0  0  1        5
2  1  1  1  0  1  1  1  0        6
3  0  1  1  1  1  1  1  0        6
4  1  1  1  0  1  0  0  1        5

In [8]:
(flips.n_heads == 3).mean()

0.22193

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [9]:
n_sim = 100_000
n_driveby = 2

billboards = np.random.choice([1,0], size=(n_sim, n_driveby), p=[.25, .75])

billboards


array([[1, 1],
       [0, 1],
       [0, 0],
       ...,
       [1, 0],
       [0, 0],
       [0, 1]])

In [10]:
ds_billboards = billboards.sum(axis = 1)

ds_billboards

array([2, 1, 0, ..., 1, 0, 1])

In [11]:
(ds_billboards == 2).mean()

0.06242

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [12]:
# np.random.normal(mean, sd)

poptarts = 17

days = 5 

n_sim = 10_000

poptarts_bought = np.random.normal(3, 1.5, size=(n_sim, days))
poptarts_bought

array([[3.98606259, 2.6196997 , 5.05620776, 3.02067253, 2.5982819 ],
       [2.79309394, 0.01359007, 3.43711199, 1.70072285, 4.31287367],
       [2.85258237, 2.84341372, 4.24598486, 4.84900805, 2.80577614],
       ...,
       [4.76696164, 2.70514418, 2.96776868, 3.2283476 , 1.54350808],
       [4.86890884, 4.0518079 , 3.14311241, 4.44583358, 2.07349993],
       [4.87942438, 5.40436521, 1.62282509, 3.74647476, 2.19068337]])

In [13]:
remaining_poptarts = poptarts - poptarts_bought.sum(axis = 1)
remaining_poptarts

array([-0.28092447,  4.74260748, -0.59676513, ...,  1.78826981,
       -1.58316265, -0.8437728 ])

In [14]:
(remaining_poptarts >= 1).mean()

0.6222

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [17]:
n_sim = 10_000

male_height = np.random.normal(178, 8, size = n_sim)

female_height = np.random.normal(170, 6, size = n_sim)

In [18]:
woman_is_taller = (female_height > male_height).mean()
woman_is_taller

0.2172

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

    What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?